### ISSUE TITLE
Resolving dependencies in the ConfigureMultitenantContainer

### ISSUE THREAD

**Issue by suwarnoong** [autofac/Autofac.AspNetCore.Multitenant#14]
Not an issue but a question instead.

I am trying to resolve `ITenantIdentificationStrategy` in the `ConfigureMultitenantContainer` but I am having `An unhandled exception of type 'Autofac.Core.DependencyResolutionException' occurred in Autofac.dll`.

```
    public static MultitenantContainer ConfigureMultitenantContainer(IContainer container)
    {
      var strategy = container.Resolve<ITenantIdentificationStrategy>();
      var mtc = new MultitenantContainer(strategy, container);
      // mtc.ConfigureTenant("a", cb => cb.RegisterType<TenantACustom>().As<ITenantCustom>());
      return mtc;
    }
```

I need to resolve `ITenantIdentificationStrategy` as it requires other dependencies. My `ITenantIdentificationStrategy` is implemented this way:
```
    public TenantResolverStrategy(
      IHttpContextAccessor httpContextAccessor,
      IMemoryCache memoryCache,
      TenantEntity tenantEntity
    )
    {
      this.httpContextAccessor = httpContextAccessor;
      this.memoryCache = memoryCache;
      this.tenantEntity = tenantEntity;
    }

    public bool TryIdentifyTenant(out object tenantId)
    {
      tenantId = null;

      var context = httpContextAccessor.HttpContext;
      var hostName = context?.Request?.Host.Value;

      tenantEntity = GetTenant(hostName);
      if (tenantEntity != null)
      {
        tenantId = tenantEntity.TenantCode;
      }

      return (tenantId != null || tenantId == (object)"");
    }
```

Program.cs
```
    var host = Host.CreateDefaultBuilder(args)
        .UseServiceProviderFactory(new AutofacMultitenantServiceProviderFactory(Startup.ConfigureMultitenantContainer))
```

I couldn't resolve other dependencies which I register in the `ConfigureContainer` as well. Is there anything wrong with my implementation?

**Comment by tillig** [comment]
As noted in the issue template, please ask usage questions on StackOverflow. It helps us answer the question for a lot of people (so if others have the same question they can find the answer) and there are more than just project owners there that can help.

> Try StackOverflow! If you have a _usage question_ ("How do I...?" "Others have this working but I can't get it...") please try [StackOverflow](https://stackoverflow.com) and tag your question `autofac`. We, along with a great community, monitor those questions.
