### ISSUE TITLE
ASP.NET Core 2.1 requires API change in middleware

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.AspNetCore.Multitenant#2]
Based on PR #1 - ASP.NET Core 2.1 introduces a breaking change in the `RequestServicesFeature` used in `MultitenantRequestServicesMiddleware`. We need to see how it'll be possible to continue support for pre-2.1 ASP.NET Core while accounting for the upcoming changes.

**Comment by tillig** [comment]
As it turns out, even with the change to middleware in this project [the changes in ASP.NET Core 2.1](https://github.com/aspnet/Hosting/issues/1377) have broken the way we hooked into replacing the request services. I've filed an issue over there to see what alternatives we have, possibly putting back a null check in there that will help get things working again.

**Comment by tillig** [comment]
The ASP.NET team fixed the issue in 2.1 so it should work again when the next preview is released. I will wait a bit and let the change make it into one of the nightly builds so I can test it out early; but there's nothing I can do for ASP.NET Core 2.1 preview 2.

**Comment by tillig** [comment]
I've pushed a fix for the API change in `RequestServicesFeature` and I've verified it still works in ASP.NET Core < 2.1. I can't verify the fix for 2.1 until a new preview build is released that includes the fix in their middleware and their nightly builds seem to have been turned off for a bit, possibly waiting for a preview 3 to start.

I'll leave this issue open until I can verify the fix against a 2.1 preview build.

**Comment by seriouz** [comment]
Can't wait for preview 3!

**Comment by tillig** [comment]
The ASP.NET Core change we required is in 2.1.0-rc1-final. I've verified that the Autofac multitenant support here does work with that. I've released [1.0.1-rc1](https://www.nuget.org/packages/Autofac.AspNetCore.Multitenant/1.0.1-rc1) to NuGet for folks to try out. When ASP.NET Core 2.1.0 is released I'll release a finished 1.0.1.

**Comment by tillig** [comment]
Pushed as [1.0.1](https://www.nuget.org/packages/Autofac.AspNetCore.Multitenant/1.0.1).
