### ISSUE TITLE
asp.net core 3.1 + autofac multitenancy and action filters

### ISSUE THREAD

**Issue by ripebananas** [autofac/Autofac.AspNetCore.Multitenant#21]
Hello, I am having an slight issue with autofac multitenancy when used in asp.net core 3.1 application with action filters.

### How to reproduce
```
git clone https://github.com/ripebananas/issues-AutofacMultitenancyAndActionFilters.git
cd issues-AutofacMultitenancyAndActionFilters\AutofacMultitenancyAndActionFilters\
dotnet run
```
browse http://localhost:5000/home - the response will display some text with type information

### Description
I have followed the guidelines for setting-up an asp.net core 3.1 app with autofac multitenancy enabled. The application has one action filter factory registered like this in the Startup.cs:

`services.AddControllers(opts => opts.Filters.Add<CustomActionFilterFactory>());`

The CustomActionFilterFactory class looks like this (the non-important stuff has been skipped):
```
public class CustomActionFilterFactory : IFilterFactory
{
    public CustomActionFilterFactory(IServiceProvider serviceProvider) { ... }

    public IFilterMetadata CreateInstance(IServiceProvider serviceProvider) { ... }
}
```

Now the interesting part is the types of the `serviceProvider` injected into the constructor and the CreateInstance method. The constructor gets an `AutofacMultitenantServiceProvider`, while the CreateInstance method gets an `AutofacServiceProvider` object injected into it.

Originally, the action filter factory did not have any constructor and I was using the service provider injected into the CreateInstance method. This caused a bunch of dependency resolution issues until I realized that the service provider is actually of type `AutofacServiceProvider` and not `AutofacMultitenantServiceProvider`.
Is this an expected behavior? If not - should I stick with the workaround of using the constructor-injected `AutofacMultitenantServiceProvider` instance or there is better workaround?

Thank you.

**Comment by tillig** [comment]
I believe this is the correct behavior. The filter factory is likely a singleton within ASP.NET Core so the service provider injected will be the "root" service provider. However, when you create filter instances it's on a per-request basis so the `CreateInstance` method will get the per-request set of services - a service provider that is already associated with a request lifetime scope based on the tenant.

It would be easy enough to test that theory by sticking a breakpoint in the `CreateInstance` method and diving in there to look at the lifetime scope around which it's wrapped. However, I don't have the time at the moment to write that test for you.

If you'd like to verify that is the behavior for a filter factory, the right folks to ask are the ASP.NET Core team. However, it makes sense that's how it'd work. It's expensive to new-up stuff that has to exist on every request and doesn't change; they've done this sort of "singleton factory" thing before in WebAPI, too.
