### ISSUE TITLE
Docs only provide example for ASP.NET Core 3.0+

### ISSUE THREAD

**Issue by mrtristan** [autofac/Autofac.AspNetCore.Multitenant#26]
Effort was taken (appreciate it!) to provide examples for pre-3.0 implementations throughout the docs. The example for Multitenant [here](https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#multitenant-support) only provides an example for what seems to be for ASP.NET Core 3.0+. While this is normally not a problem, this implementation happens to touch on areas that are rather different as compared to 1.x-2.x. Any chance that there's some "old docs" laying around that could be injected (no pun intended) in there to continue on in the spirit of providing both examples?

One such pain point that's causing an obscene amount of googling is the whole generic `HostBuilder` vs `WebHostBuilder` and not being able to call something like `.UseServiceProviderFactory(new AutofacMultitenantServiceProviderFactory(Startup.ConfigureMultitenantContainer))` when using a `WebHost`

**Comment by alsami** [comment]
Hey @mrtristan,

I appreciate your feedback. Did you check out the samples folder in this [repository](https://github.com/autofac/Autofac.AspNetCore.Multitenant/tree/develop/samples/Sandbox.AspNetCore2_1_To_2_2)?

There's an updated example for >= 2.1x of ASP.NET Core available.

Basically, what you need now is the following

```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
	WebHost.CreateDefaultBuilder(args)
		.UseStartup<Startup>()
		.UseAutofacMultitenantRequestServices()
		.ConfigureServices(sp =>
		{
			sp.AddSingleton<IServiceProviderFactory<ContainerBuilder>>(
				new AutofacMultitenantServiceProviderFactory(MultitenantContainerSetup
					.ConfigureMultitenantContainer));
		});
```

**Comment by mrtristan** [comment]
thanks for the quick response. i had actually tried that yes, and coupled it with the following in `Startup`:

```c#
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    services
        .AddSignalR()
        .AddJsonProtocol(options => options.PayloadSerializerSettings.ContractResolver = new DefaultContractResolver());

    services.AddHttpContextAccessor();
    services.AddSingleton<IActionContextAccessor, ActionContextAccessor>();
    services.AddHttpClient();

    services
        .AddMvc(options => { options.Filters.Add(new ResponseCacheAttribute {NoStore = true, Location = ResponseCacheLocation.None}); })
        .AddControllersAsServices()
        .AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());

    var containerBuilder = new ContainerBuilder();
    containerBuilder.Populate(services);

    containerBuilder.RegisterType<XXX>().InstancePerLifetimeScope();
    containerBuilder.RegisterType<TenantIdentificationStrategy>().SingleInstance();

    var container = containerBuilder.Build();
    
    var strategy = container.Resolve<TenantIdentificationStrategy>();

    var mtc = new MultitenantContainer(strategy, container);

    mtc.ConfigureTenant(
                         "a",
                         cb =>
                         {
                             //
                         });
    mtc.ConfigureTenant(
                         "GRDEV",
                         cb =>
                         {
                             //
                             
                         }
                        );

    return new AutofacServiceProvider(mtc);
}
```

In trying this, i was getting errors about the root container not being a multi tenant container like: `The multitenant container accessor didn't provide a multitenant container. Check your UseAutofacMultitenantRequestServices method call to ensure the container accessor is correctly set up`. I was also seeing that breakpoints wouldn't hit when trying to stop in `ConfigureMultitenantContainer` when going with

```c#
sp.AddSingleton<IServiceProviderFactory<ContainerBuilder>>(
				new AutofacMultitenantServiceProviderFactory(MultitenantContainerSetup
					.ConfigureMultitenantContainer));
```

any thoughts on the approach? when going with your example, should `MultitenantContainerSetup.ConfigureMultitenantContainer` handle the entirety of all registrations or should it only handle the tenant specific registrations? if not, where do you do "normal" registrations?

thanks!

**Comment by tillig** [comment]
Try adding an empty ConfigureContainer method like you see in the example. It has to have the same signature but the contents can be empty.

I'm vaguely recalling that if you don't have ConfigureContainer then ASP.NET skips a lot of setup in an attempt to optimize.

If you have that... Then maybe include your whole Startup here instead of just a snip.

**Comment by mrtristan** [comment]
sure. i'll try and get a minimum repro going. i did also try having that empty method last night. i put a stop in it though and didn't trip whatever that's worth.

**Comment by alsami** [comment]
> any thoughts on the approach? when going with your example, should `MultitenantContainerSetup.ConfigureMultitenantContainer` handle the entirety of all registrations or should it only handle the tenant specific registrations? if not, where do you do "normal" registrations?

I am really not sure if the latest version would work with the old fashioned `return IServiceProvider from ConfigureServices`.

So basically, going through it what you need is the following...

Program.cs

```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
	WebHost.CreateDefaultBuilder(args)
		.UseStartup<Startup>()
		.UseAutofacMultitenantRequestServices()
		.ConfigureServices(sp =>
		{
			sp.AddSingleton<IServiceProviderFactory<ContainerBuilder>>(
				new AutofacMultitenantServiceProviderFactory(Startup
					.ConfigureMultitenantContainer));
		});
```

Startup.cs

```csharp
public class Startup
{
   public void ConfigureServices(IServiceCollection services)
   {
        // here you should register framework dependencies for ASP.NET Core.
       // you can still do other service registrations, if you insist on it
       services.AddMvc(); // and all the usual stuff
   }
   
   public void Configure(IApplicationBuilder app)
   {
       app.UseMvc(); // and all the usual stuff
   }

    // this magic method will be called from the AutofacMultitenantServiceProviderFactory and must be available!
   public void ConfigureContainer(ContainerBuilder builder)
   {
       // here you add all the dependencies that shall be available for the whole application, independent of the tenant
   }
  
   // this will be called from the AutofacMultitenantServiceProviderFactory
   public static MultitenantConainer ConfigureMultitenantContainer(IContainer container)
   {
      var strategy = // construct your tenant identification strategy here
      var mtc = new MultitenantContainer(strategy, container);
      mtc.ConfigureTenant(...); // the usual
   }
}
```

Remember that everything you are registering for a tenant must have a default implementation as well, otherwise you will end up having runtime errors where specific services can't be resolved.

**Comment by mrtristan** [comment]
what you just described as the "old fashioned" way in using `return IServiceProvider from ConfigureServices` i think was my problem. in doing things how you just mentioned, i think things are working.

for what it's worth, my current requirements dictate that i target `net472` and manually reference `Microsoft.AspNetCore` at `2.2.0`. not sure if that adds any variability.

**Comment by alsami** [comment]
> for what it's worth, my current requirements dictate that i target `net472` and manually reference `Microsoft.AspNetCore` at `2.2.0`. not sure if that adds any variability.

That shouldn't be a problem. This library targets `netstandard2.0` and `net472` fully supports that w/o additional bindings.

The old fashioned way was the first possibility for third-party IoC providers to hook into ASP.NET Core. It was introduced with 1.1 and with 2.0 (AFAIK) they made it possible to define the described custom delegate within the `Startup` class. Meaning, you should be good to update the usage to the new version.

If you are having problems and you can provide the code or a repro sample, let me know, I'll be sending you a PR then.

**Comment by tillig** [comment]
[I thought they stopped supporting net472 with ASP.NET Core 2.1](https://github.com/aspnet/Announcements/issues/324).

**Comment by alsami** [comment]
> [I thought they stopped supporting net472 with ASP.NET Core 2.1](https://github.com/aspnet/Announcements/issues/324).

Only for >= 3.0, no?

[Microsoft.AspNetCore package](https://www.nuget.org/packages/Microsoft.AspNetCore/2.2.0) works fine with <= ASP.NET Core 2.2 and full .NET-Framework. All dependencies of that package target `.netstandard2.0`. With Visual Studio 2017 they even had a template to create a new ASP.NET Core Application with full .NET-Framework.

-- EDIT --

Just double checked, The template is still available on VS19.

![image](https://user-images.githubusercontent.com/2729205/77990123-ca653700-7320-11ea-9509-14285aaf89ff.png)

It creates the project targeting `net461`. You can simply change it to `net472`. I think this announcement was before ASP.NET Core 2.2 even existed.

**Comment by alsami** [comment]
@mrtristan I am closing the issue now. If the provided sample does not work for you, please feel free to reopen it and create a small repo for reproduction.
