### ISSUE TITLE
A.E.DI 8.0 breaks multitenant support

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac.AspNetCore.Multitenant#43]
8.0.0 has released, package needs to be aligned

**Comment by tillig** [comment]
I updated the [A E.DI release notes](https://github.com/autofac/Autofac.Extensions.DependencyInjection/releases/tag/v8.0.0) to mention that this is broken. I'll remove that warning when it's fixed.

For other folks coming in: the change in how lifetime scopes work is what broke things here. We'd not have changed that, but without scopes handled in this "flat" way, we're not compatible with the stock Microsoft container. This is the price for conforming container support.

**Comment by tillig** [comment]
Updated issue title. While the goal here is to update support, it's not obvious to folks coming in WHY we need to update. Hoping this stops more duplicates from being filed.

**Comment by tillig** [comment]
Fixed bu #44.
