### ISSUE TITLE
Add support to .NET 8

### ISSUE THREAD

**Issue by Robbware** [autofac/Autofac.AspNetCore.Multitenant#50]
## Problem Statement

With the changes done on the main library when bumping to 8.0.0, it'd be nice to also have this one updated!

## Desired Solution

Update lib to .NET 8/add support to Autofac 8.0.0.

## Alternatives You've Considered

Ignoring the autofac version bump for now 😢

**Comment by tillig** [comment]
Is there an error you get on upgrade?

**Comment by liphvf** [comment]
In my case, this message appear after update to autofac 8 dotnet 8.

Erro:
```
Exception has occurred: CLR/System.TypeLoadException
An unhandled exception of type 'System.TypeLoadException' occurred in System.Private.CoreLib.dll: 'Method 'ResolveComponent' in type 'Autofac.Multitenant.MultitenantContainer' from assembly 'Autofac.Multitenant, Version=7.0.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' does not have an implementation.'
```

csproj:
```
        <PackageReference Include="Autofac" Version="8.0.0" />
        <PackageReference Include="Autofac.AspNetCore.Multitenant" Version="7.0.0" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
```

**Comment by tillig** [comment]
OK, I see what's up. It's not a .NET 8 upgrade, it's specifically Autofac 8 and the one breaking change that got introduced. Let me see what I can do.

**Comment by tillig** [comment]
In working on this update I found an error in the nullable type annotations on Autofac.Multitenant, so I have a [PR in for that, too](https://github.com/autofac/Autofac.Multitenant/pull/39). I'll try to incorporate that update here as well.
