### ISSUE TITLE
Multitenant setup not working with aspnetcore 2.2

### ISSUE THREAD

**Issue by okoaset** [autofac/Autofac.AspNetCore.Multitenant#6]
I followed the aspnetcore multitenant documentation, but still getting default services picked up.  Below is code for configureServices. 

``` public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            var builder = new ContainerBuilder();
            builder.Populate(services);
            builder.RegisterType<HttpHeaderTenantIdentificationService>().As<ITenantIdentificationStrategy>();
            builder.RegisterType<DefaultSomeService>().As<ISomeService>();
            var container = builder.Build();

            var multiTenantContainer = new MultitenantContainer(container.Resolve<ITenantIdentificationStrategy>(), container);


            multiTenantContainer.ConfigureTenant("1", m =>
            {
                m.RegisterType<TestSomeService>()
                  .As<ISomeService>()
                  .InstancePerLifetimeScope();  
            });

            Startup.ApplicationContainer = multiTenantContainer;
            return new AutofacServiceProvider(multiTenantContainer);
        }
```

```public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseAutofacMultitenantRequestServices(() => Startup.ApplicationContainer)
                .UseStartup<Startup>();
    } 
 ```

**Comment by tillig** [comment]
The [Sandbox example in this repo](https://github.com/autofac/Autofac.AspNetCore.Multitenant/blob/develop/samples/Sandbox/README.md) is using ASP.NET Core 2.2 and the setup looks almost identical to yours. It seems to work. I am guessing it has something to do with your `HttpHeaderTenantIdentificationService`. Try adding some debug logging in there to see if it's getting called. If it's not called, that's a problem. If it is called, ensure it's successfully identifying the tenant.

For example, I don't see any registration around `IHttpContextAccessor` so I'm not sure how your header identification strategy is getting the `HttpContext` from which the headers would be read. That's not registered in `services.AddMvc()` by default; they stopped doing that in ASP.NET Core 1.1 or so.
