### ISSUE TITLE
Multi-Tenant Authentication

### ISSUE THREAD

**Issue by justinhelgerson** [autofac/Autofac.AspNetCore.Multitenant#8]
I was wondering if anyone has used the Autofac Multitenant implementation to setup dynamic authentication per tenant.  As an example, Tenant1 may use Open Id Connect (OIDC) with Okta, while Tenant2 may use OIDC with AWS Cognito.

Is it possible to leverage the multitenant library to help with this?

**Comment by tillig** [comment]
We can supply dependencies by tenant but we don't do anything with authentication. If you want to switch auth by tenant, you'd have to make your authentication components dependencies that can be injected into... wherever you need them. We have no application-specific recommendations on how to accomplish that, sorry.
